### ISSUE TITLE
scrapper.rb:79:in `fetch_editorialgroup`: undefined method `text` for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Intelligent2013** [relaton/relaton-bsi#3]
### Stack trace:
```
17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-96bd14c2a61a/lib/asciidoctor/standoc/ref.rb:213:in `reference1'
16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-96bd14c2a61a/lib/asciidoctor/standoc/ref.rb:154:in `refitem'
15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-96bd14c2a61a/lib/asciidoctor/standoc/ref.rb:162:in `refitem1'
14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-96bd14c2a61a/lib/asciidoctor/standoc/ref_sect.rb:70:in `fetch_ref'
13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.8.1/lib/relaton/db.rb:73:in `fetch'
12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.8.1/lib/relaton/db.rb:385:in `check_bibliocache'
11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.8.1/lib/relaton/db.rb:405:in `new_bib_entry'
10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.8.1/lib/relaton/db.rb:420:in `net_retry'
9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/processor.rb:17:in `get'
8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/bsi_bibliography.rb:34:in `get'
7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/bsi_bibliography.rb:100:in `bib_get1'
6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/bsi_bibliography.rb:86:in `isobib_results_filter'
5: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `each'
4: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `each'
3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/bsi_bibliography.rb:89:in `block in isobib_results_filter'
2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/hit.rb:11:in `fetch'
1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/scrapper.rb:24:in `parse_page'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/scrapper.rb:79:in `fetch_editorialgroup': undefined method `text' for nil:NilClass (NoMethodError)
```

### How to reproduce:
- `git clone https://github.com/metanorma/mn-samples-bsi`
- `bundle exec metanorma -t bsi -x presentation sources.mnconvert/bs-codes-of-practice/bs-7273-4-2015-A1-2021/document.adoc`

Source: https://github.com/metanorma/mnconvert/issues/37

This error occurs due this line in `02-normrefs.adoc`:

```adoc
* [[[BS_EN_61386-1,BS EN 61386-1]]], _Conduit systems for cable management – Part 1: General requirements_
```

**Comment by andrew2net** [comment]
@ronaldtse for the `BS EN 61386-1` reference the https://shop.bsigroup.com/SearchResults finds 3 documents:
- [BS EN 61386-1:2008+A1:2019 - TC](https://shop.bsigroup.com/ProductDetail?pid=000000000030407523)
- [BS EN 61386-1:2008+A1:2019](https://shop.bsigroup.com/ProductDetail?pid=000000000030340237)
- [BS EN 61386-1:2004](https://shop.bsigroup.com/ProductDetail?pid=000000000030103264)

The first document is the latest. It seems the last document is replaced by the second.
Which of these 3 documents should the `relaton-bsi` return?

**Comment by ronaldtse** [comment]
Whoa very good question!! According to ISO 690 it is the first one (because I wrote that bit) :wink:

**Comment by andrew2net** [comment]
The first document is returned now. The bug is fixed.
